import { defineConfig, globalIgnores } from 'eslint/config'
import nextVitals from 'eslint-config-next/core-web-vitals'
import nextTs from 'eslint-config-next/typescript'
import jsxA11y from 'eslint-plugin-jsx-a11y'
import prettier from 'eslint-config-prettier'

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // JSX accessibility rules (recommended ruleset)
  {
    rules: {
      ...jsxA11y.configs.recommended.rules,
      'react-hooks/set-state-in-effect': 'off',
      'react/no-unescaped-entities': 'off',
    },
  },
  // Prettier - must be last to override conflicting rules
  prettier,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    // Skip nested build output inside git worktrees (e.g. `.claude/worktrees/*/.next/`),
    // which the root-anchored `.next/**` pattern above doesn't catch.
    '**/.next/**',
    '.claude/worktrees/**',
    // Generated by `npx supabase start` (Edge Runtime bootstrap secrets).
    // Gitignored but not previously ESLint-ignored, so a local Supabase
    // restart made `npm run lint` fail on that machine.
    'supabase/.temp/**',
  ]),
])

export default eslintConfig
