import { type RouteCollection } from "@/components/routes-page";

// Placeholder routes - replace with actual data per chapter
export const placeholderRouteCollections: RouteCollection[] = [
  {
    name: "200 km Brevets",
    routes: [
      { name: "Aldershot Erie", distance: "200", url: "https://ridewithgps.com/routes/50952805" },
      { name: "Bewdley Glutebuster", distance: "200", url: "https://www.randonneursontario.ca/routes/gmap400.php?scale=auto&path=torroutes&track=Bewdley_Glutebuster_200.gpx" },
      { name: "Big Chute", distance: "200", url: "https://ridewithgps.com/routes/20901018" },
      { name: "Bits n Pieces", distance: "200", url: "https://www.randonneursontario.ca/routes/gmap400.php?scale=auto&path=torroutes&track=Bits_And_Pieces_200.gpx" },
      { name: "Castle", distance: "200", url: "https://ridewithgps.com/routes/25673993" },
      { name: "Concord Orangeville", distance: "200", url: "https://www.randonneursontario.ca/routes/gmap400.php?scale=auto&path=torroutes&track=Concord_Orangeville_200.gpx" },
      { name: "Concord Orillia", distance: "200", url: "https://ridewithgps.com/routes/27004893" },
      { name: "Gentle Start Erin Mills", distance: "200", url: "https://www.randonneursontario.ca/routes/gmap400.php?scale=auto&path=torroutes&track=Gentle_Start_Erin_Mills_200.gpx" },
      { name: "Gentle Start (Glen Morris Edition)", distance: "200", url: "https://ridewithgps.com/routes/49502876" },
      { name: "Gentle Start Oakville", distance: "200", url: "https://ridewithgps.com/routes/27004587" },
      { name: "Grand River", distance: "200", url: "https://ridewithgps.com/routes/21462516" },
      { name: "Hills of Hockley", distance: "200", url: "https://ridewithgps.com/routes/22030932" },
      { name: "Mariposa", distance: "200", url: "https://ridewithgps.com/routes/37167462" },
      { name: "Markham Woodville", distance: "200", url: "https://ridewithgps.com/routes/20584348" },
      { name: "Niagara Plateau", distance: "200", url: "https://ridewithgps.com/routes/32142325" },
      { name: "Niagara Ramble", distance: "200", url: "https://ridewithgps.com/routes/23231984" },
      { name: "Rockwood", distance: "200", url: "https://ridewithgps.com/routes/40163844" },
      { name: "Scugog Circle", distance: "200", url: "https://ridewithgps.com/routes/20658939" },
      { name: "Six Nations", distance: "200", url: "https://ridewithgps.com/routes/27429598" },
      { name: "Tour of the Valleys", distance: "200", url: "https://ridewithgps.com/routes/23203003" },
      { name: "Urban Start", distance: "200", url: "https://ridewithgps.com/routes/20586376" },
      { name: "Warmup", distance: "200", url: "https://ridewithgps.com/routes/39130100" },
      { name: "Waterfront East", distance: "200", url: "https://ridewithgps.com/routes/20784084" },
    ],
  },
  {
    name: "Populaires",
    routes: [
      { name: "Bewdley", distance: "160", url: "https://ridewithgps.com/routes/49728359" },
      { name: "Belfountain", distance: "160", url: "https://ridewithgps.com/routes/53382394" },
      { name: "Concord Bradford", distance: "90", url: "https://ridewithgps.com/routes/22029018" },
      { name: "Concord Belfountain", distance: "135", url: "https://ridewithgps.com/routes/26719432" },
      { name: "Erin Mills-Erin", distance: "130", url: "https://ridewithgps.com/routes/27004522" },
      { name: "E-Z Toronto Loop", distance: "92", url: "https://ridewithgps.com/routes/32463456" },
      { name: "Gentle Start", distance: "120", url: "https://ridewithgps.com/routes/49732622" },
      { name: "Imperial Rouge", distance: "160", url: "https://ridewithgps.com/routes/29704740" },
      { name: "Lakes and Vibes", distance: "160", url: "https://ridewithgps.com/routes/49732917" },
      { name: "Mono-Creemore Escarpment Surfing", distance: "100", url: "https://ridewithgps.com/routes/35571057" },
      { name: "New Years", distance: "25", url: "https://ridewithgps.com/routes/38242529" },
      { name: "Old Toronto", distance: "53", url: "https://ridewithgps.com/routes/32596016" },
      { name: "Port Perry", distance: "160", url: "https://ridewithgps.com/routes/49728359" },
      { name: "Rouge Ramble", distance: "60", url: "https://ridewithgps.com/routes/27003525" },
      { name: "Saddle Sister", distance: "34", url: "https://ridewithgps.com/routes/40880296" },
      { name: "Uxbridge Ice Classic", distance: "110", url: "https://ridewithgps.com/routes/26478187" },
    ],
  },
];

// Toronto-specific routes
export const torontoRouteCollections: RouteCollection[] = [
  {
    name: "200 km Brevets",
    routes: [
      { name: "Aldershot Erie", distance: "200", url: "https://ridewithgps.com/routes/50952805" },
      { name: "Bewdley Glutebuster", distance: "200", url: "https://www.randonneursontario.ca/routes/gmap400.php?scale=auto&path=torroutes&track=Bewdley_Glutebuster_200.gpx" },
      { name: "Big Chute", distance: "200", url: "https://ridewithgps.com/routes/20901018" },
      { name: "Bits n Pieces", distance: "200", url: "https://www.randonneursontario.ca/routes/gmap400.php?scale=auto&path=torroutes&track=Bits_And_Pieces_200.gpx" },
      { name: "Castle", distance: "200", url: "https://ridewithgps.com/routes/25673993" },
      { name: "Concord Orangeville", distance: "200", url: "https://www.randonneursontario.ca/routes/gmap400.php?scale=auto&path=torroutes&track=Concord_Orangeville_200.gpx" },
      { name: "Concord Orillia", distance: "200", url: "https://ridewithgps.com/routes/27004893" },
      { name: "Gentle Start Erin Mills", distance: "200", url: "https://www.randonneursontario.ca/routes/gmap400.php?scale=auto&path=torroutes&track=Gentle_Start_Erin_Mills_200.gpx" },
      { name: "Gentle Start (Glen Morris Edition)", distance: "200", url: "https://ridewithgps.com/routes/49502876" },
      { name: "Gentle Start Oakville", distance: "200", url: "https://ridewithgps.com/routes/27004587" },
      { name: "Grand River", distance: "200", url: "https://ridewithgps.com/routes/21462516" },
      { name: "Hills of Hockley", distance: "200", url: "https://ridewithgps.com/routes/22030932" },
      { name: "Loyalist (Napanee Start)", distance: "200", url: "https://www.randonneursontario.ca/routes/torroutes/Loyalist_Napanee_200.pdf" },
      { name: "Loyalist (Picton Start)", distance: "200", url: "https://www.randonneursontario.ca/routes/torroutes/Loyalist_200.pdf" },
      { name: "Maple-Orillia", distance: "200", url: "https://www.randonneursontario.ca/routes/torroutes/Maple-Orillia_200.pdf" },
      { name: "Mariposa", distance: "200", url: "https://ridewithgps.com/routes/37167462" },
      { name: "Markham Woodville", distance: "200", url: "https://ridewithgps.com/routes/20584348" },
      { name: "Mean Streets", distance: "200", url: "https://www.randonneursontario.ca/routes/torroutes/Mean_Streets_200.pdf" },
      { name: "M-H Roughstuff", distance: "200", url: "https://www.randonneursontario.ca/routes/torroutes/M-H_Roughstuff_200.pdf" },
      { name: "Niagara Plateau", distance: "200", url: "https://ridewithgps.com/routes/32142325" },
      { name: "Niagara Ramble", distance: "200", url: "https://ridewithgps.com/routes/23231984" },
      { name: "Rockwood", distance: "200", url: "https://ridewithgps.com/routes/40163844" },
      { name: "Scugog Circle", distance: "200", url: "https://ridewithgps.com/routes/20658939" },
      { name: "Scugog Circle Urban Start", distance: "200", url: "https://ridewithgps.com/routes/44467429" },
      { name: "Six Nations", distance: "200", url: "https://ridewithgps.com/routes/27429598" },
      { name: "Tough Tour 200 Plus", distance: "200", url: "https://www.randonneursontario.ca/routes/torroutes/Tough_Tour_200_Plus.pdf" },
      { name: "Tour of the Valleys", distance: "200", url: "https://ridewithgps.com/routes/23203003" },
      { name: "Udora-Uxbridge-Utica", distance: "200", url: "https://ridewithgps.com/routes/31544344" },
      { name: "Urban Start", distance: "200", url: "https://ridewithgps.com/routes/20586376" },
      { name: "Warmup", distance: "200", url: "https://ridewithgps.com/routes/39130100" },
      { name: "Waterfront East", distance: "200", url: "https://ridewithgps.com/routes/20784084" },
    ],
  },
  {
    name: "Populaires",
    routes: [
      { name: "Bewdley", distance: "160", url: "https://ridewithgps.com/routes/49728359" },
      { name: "Belfountain", distance: "160", url: "https://ridewithgps.com/routes/53382394" },
      { name: "Concord Bradford", distance: "90", url: "https://ridewithgps.com/routes/22029018" },
      { name: "Concord Beeton Flat", distance: "100", url: "https://www.randonneursontario.ca/routes/gmap400.php?scale=auto&path=torroutes&track=Concord_Beeton_Flat_100.gpx" },
      { name: "Concord Beeton Hilly", distance: "100", url: "https://www.randonneursontario.ca/routes/gmap400.php?scale=auto&path=torroutes&track=Concord_Beeton_Hilly_100.gpx" },
      { name: "Concord Belfountain", distance: "135", url: "https://ridewithgps.com/routes/26719432" },
      { name: "Erin Mills-Cambridge", distance: "150", url: "https://www.randonneursontario.ca/routes/torroutes/Erin_Mills-Cambridge_150.pdf" },
      { name: "Erin Mills-Campbellville", distance: "110", url: "https://www.randonneursontario.ca/routes/gmap400.php?scale=auto&path=torroutes&track=Erin_Mills_Campbellville_110.gpx" },
      { name: "Erin Mills-Erin", distance: "130", url: "https://ridewithgps.com/routes/27004522" },
      { name: "E-Z Toronto Loop", distance: "92", url: "https://ridewithgps.com/routes/32463456" },
      { name: "Erin Mills-St. George", distance: "135", url: "https://www.randonneursontario.ca/routes/torroutes/Erin_Mills-St.George_135.pdf" },
      { name: "Erin Mills-Waterdown", distance: "110", url: "https://www.randonneursontario.ca/routes/torroutes/Erin_Mills-Waterdown_110.pdf" },
      { name: "Gentle Start", distance: "120", url: "https://ridewithgps.com/routes/49732622" },
      { name: "Giro del Toronto", distance: "80", url: "https://www.randonneursontario.ca/routes/torroutes/Giro_del_Toronto_80.pdf" },
      { name: "Imperial Rouge", distance: "160", url: "https://ridewithgps.com/routes/29704740" },
      { name: "Jordan Ramble", distance: "100", url: "https://www.randonneursontario.ca/routes/torroutes/Jordan_Ramble_100.pdf" },
      { name: "Kleinburg-Tottenham", distance: "85", url: "https://www.randonneursontario.ca/routes/gmap400.php?scale=auto&path=torroutes&track=Kleinburg_Tottenham_85.gpx" },
      { name: "Lakes and Vibes", distance: "160", url: "https://ridewithgps.com/routes/49732917" },
      { name: "Maple-Barrie", distance: "135", url: "https://www.randonneursontario.ca/routes/torroutes/Maple-Barrie_135.pdf" },
      { name: "Maple-Barrie", distance: "150", url: "https://www.randonneursontario.ca/routes/torroutes/Maple-Barrie_150.pdf" },
      { name: "Maple-Bolton/Caledon East", distance: "80", url: "https://www.randonneursontario.ca/routes/torroutes/Maple-Bolton-CaledonEast.pdf" },
      { name: "Maple-Bradford", distance: "70", url: "https://www.randonneursontario.ca/routes/torroutes/Maple-Bradford_70.pdf" },
      { name: "Markham-Kirby", distance: "135", url: "https://www.randonneursontario.ca/routes/torroutes/Markham-Kirby_135.pdf" },
      { name: "Maple-Newmarket", distance: "70", url: "https://www.randonneursontario.ca/routes/gmap400.php?scale=auto&path=torroutes&track=Maple_Newmarket_70.gpx" },
      { name: "Maple-Schomberg", distance: "60", url: "https://www.randonneursontario.ca/routes/torroutes/Maple-Schomberg_60.pdf" },
      { name: "Maple-Thornton", distance: "125", url: "https://www.randonneursontario.ca/routes/torroutes/Maple-Thornton_125.pdf" },
      { name: "Maple-Tottenham", distance: "120", url: "https://www.randonneursontario.ca/routes/torroutes/Maple-Tottenham_120.pdf" },
      { name: "Maple-Uxbridge", distance: "120", url: "https://www.randonneursontario.ca/routes/torroutes/Maple-Uxbridge_120.pdf" },
      { name: "Markham-Leaksdale", distance: "110", url: "https://www.randonneursontario.ca/routes/torroutes/Markham-Leaksdale_110.pdf" },
      { name: "Markham-Port Perry", distance: "120", url: "https://www.randonneursontario.ca/routes/torroutes/Markham-Port_Perry_120.pdf" },
      { name: "Markham-Udora", distance: "120", url: "https://www.randonneursontario.ca/routes/torroutes/Markham-Udora_120.pdf" },
      { name: "Mono-Creemore Escarpment Surfing (Gravel)", distance: "100", url: "https://ridewithgps.com/routes/35571057" },
      { name: "New Years", distance: "25", url: "https://ridewithgps.com/routes/38242529" },
      { name: "Oakville-Acton", distance: "120", url: "https://www.randonneursontario.ca/routes/torroutes/Oakville-Acton_120.pdf" },
      { name: "Oakville-Campbellville", distance: "85", url: "https://www.randonneursontario.ca/routes/torroutes/Oakville-Campbellville_85.pdf" },
      { name: "Oakville-St.George", distance: "140", url: "https://www.randonneursontario.ca/routes/torroutes/Oakville-St.George Populaire.pdf" },
      { name: "Old Toronto", distance: "53", url: "https://ridewithgps.com/routes/32596016" },
      { name: "Port Perry", distance: "160", url: "https://ridewithgps.com/routes/49728359" },
      { name: "Rouge Ramble", distance: "60", url: "https://ridewithgps.com/routes/27003525" },
      { name: "Saddle Sister", distance: "34", url: "https://ridewithgps.com/routes/40880296" },
      { name: "Simcoe Century", distance: "165", url: "https://www.randonneursontario.ca/routes/gmap400.php?scale=auto&path=torroutes&track=Simcoe_Century_165.gpx" },
      { name: "The Scarborough Scramble", distance: "80", url: "https://www.randonneursontario.ca/routes/torroutes/The_Scarborough_Scramble.pdf" },
      { name: "Uxbridge Ice Classic", distance: "110", url: "https://ridewithgps.com/routes/26478187" },
    ],
  },
  {
    name: "Devil Week 2026",
    routes: [
      { name: "DW Niagara Rambulaire", distance: "100", url: "https://ridewithgps.com/routes/52982491" },
      { name: "DW Niagara Ramble", distance: "200", url: "https://ridewithgps.com/routes/23231984" },
      { name: "DW Lakes and Vines", distance: "300", url: "https://ridewithgps.com/routes/52940091" },
      { name: "DW Niagara Peninsula", distance: "400", url: "https://ridewithgps.com/routes/53015006" },
      { name: "DW The Great Grimsby Gambit", distance: "600", url: "https://ridewithgps.com/routes/53043779" },
    ],
  },
  {
    name: "Devil Week 2015",
    routes: [
      { name: "DW Woodville", distance: "200", url: "https://www.randonneursontario.ca/routes/gmap400.php?scale=auto&path=torroutes&track=DW_Woodville_200.gpx" },
      { name: "DW Carden Plain", distance: "300", url: "https://www.randonneursontario.ca/routes/gmap400.php?scale=auto&path=torroutes&track=DW_Carden_Plain_300.gpx" },
      { name: "DW Oak Ridges Moraine", distance: "400", url: "https://www.randonneursontario.ca/routes/gmap400.php?scale=auto&path=torroutes&track=DW_Oak_Ridges_Moraine_400.gpx" },
      { name: "DW Haliburton Highlands", distance: "600", url: "https://www.randonneursontario.ca/routes/gmap400.php?scale=auto&path=torroutes&track=DW_Haliburton_Highlands_600.gpx" },
    ],
  },
];
