#!/bin/bash
# Generate a clean seed.sql file from the current database state
# This avoids the backslash escape issues that pg_dump can introduce

set -e

SEED_FILE="supabase/seed.sql"
CONTAINER="supabase_db_randonneurs-ontario"

echo "Generating seed file from current database…"

# Generate the dump with INSERT statements using pg_dump from inside Docker
# (to avoid version mismatch issues)
# --data-only: Only data, no schema
# --inserts: Use INSERT instead of COPY (avoids escape issues)
# --column-inserts: Include column names in INSERT statements
# --no-comments: Skip comments
# --rows-per-insert=1: One row per INSERT for easier debugging
docker exec "$CONTAINER" pg_dump -U postgres \
  --data-only \
  --inserts \
  --column-inserts \
  --no-comments \
  --rows-per-insert=1 \
  --schema=public \
  --exclude-table=admins \
  --exclude-table=images \
  --exclude-table=rider_memberships \
  postgres > "$SEED_FILE.tmp"

# Clean up the file:
# 1. Remove SET statements (they can cause issues)
# 2. Remove backslash commands like \connect, \restrict
# 3. Remove empty lines at the start
# 4. Keep only INSERT statements and necessary transaction commands
grep -E "^(INSERT INTO|SELECT pg_catalog|--|$)" "$SEED_FILE.tmp" | \
  grep -v "^--" | \
  grep -v "^SELECT pg_catalog" | \
  grep -v "^$" > "$SEED_FILE.tmp2" || true

# Convert chapter INSERTs to use ON CONFLICT DO UPDATE
# This ensures correct UUIDs even when migrations have already inserted some chapters
# The migration uses ON CONFLICT DO NOTHING, so seed needs to update the IDs
sed -i.bak 's/INSERT INTO public\.chapters (\([^)]*\)) VALUES (\([^)]*\));/INSERT INTO public.chapters (\1) VALUES (\2) ON CONFLICT (slug) DO UPDATE SET id = EXCLUDED.id, name = EXCLUDED.name, description = EXCLUDED.description, founded_year = EXCLUDED.founded_year;/' "$SEED_FILE.tmp2"
rm -f "$SEED_FILE.tmp2.bak"

# Strip PII from rider rows: null out email, emergency_contact_name,
# emergency_contact_phone, ccn_id, birth_year (columns 5, 9, 10, 12, 13)
# Column order from pg_dump: id(1), slug(2), first_name(3), last_name(4),
# email(5), gender(6), created_at(7), updated_at(8), emergency_contact_name(9),
# emergency_contact_phone(10), rider_number(11), ccn_id(12), birth_year(13),
# member_since(14)
awk '
/^INSERT INTO public\.riders / {
  # Split into prefix (before VALUES) and values
  match($0, /VALUES \(/)
  prefix = substr($0, 1, RSTART + 7)  # "... VALUES ("
  rest = substr($0, RSTART + 8)        # everything after "VALUES ("
  sub(/\);$/, "", rest)                 # remove trailing ");"

  # Parse SQL values respecting quoted strings
  n = 0
  val = ""
  in_quote = 0
  for (i = 1; i <= length(rest); i++) {
    c = substr(rest, i, 1)
    if (in_quote) {
      val = val c
      if (c == "'"'"'") {
        if (substr(rest, i+1, 1) == "'"'"'") {
          val = val substr(rest, i+1, 1)
          i++
        } else {
          in_quote = 0
        }
      }
    } else if (c == "'"'"'") {
      in_quote = 1
      val = val c
    } else if (c == ",") {
      n++
      fields[n] = val
      val = ""
      # skip space after comma
      if (substr(rest, i+1, 1) == " ") i++
    } else {
      val = val c
    }
  }
  n++
  fields[n] = val

  # Null out PII columns: 5=email, 9=emergency_contact_name,
  # 10=emergency_contact_phone, 12=ccn_id, 13=birth_year
  fields[5] = "NULL"
  fields[9] = "NULL"
  fields[10] = "NULL"
  fields[12] = "NULL"
  fields[13] = "NULL"

  # Reassemble
  line = prefix fields[1]
  for (j = 2; j <= n; j++) {
    line = line ", " fields[j]
  }
  print line ");"
  next
}
{ print }
' "$SEED_FILE.tmp2" > "$SEED_FILE.tmp3"
mv "$SEED_FILE.tmp3" "$SEED_FILE.tmp2"

# Add a header and the cleaned INSERT statements
cat > "$SEED_FILE" << 'EOF'
-- Seed data for Randonneurs Ontario
-- Generated by scripts/generate-seed.sh
--
-- Note: This file is auto-generated. Do not edit manually.
-- To regenerate: ./scripts/generate-seed.sh
--
-- Tables seeded (in order):
-- 1. chapters
-- 2. awards
-- 3. riders
-- 4. routes
-- 5. events
-- 6. results
-- 7. result_awards
-- 8. rider_awards
-- 9. registrations
--
-- Note: admins table is NOT included (requires auth.users)
-- Use scripts/create-admin.ts to create admin users after seeding.
--
-- PII stripped: rider email, emergency contacts, ccn_id, birth_year are NULL.
-- rider_memberships excluded entirely.
-- Run seed-memberships.sql after seeding to restore PII + memberships.
-- To regenerate: ./scripts/generate-seed.sh (generates both files)

-- Restore the dump verbatim: disable triggers during the bulk load so that
-- AFTER-INSERT triggers (e.g. the First Brevet award reconciler from migration
-- 20260526120000) don't pre-create rows the dump then re-inserts, which crashes
-- a fresh seed with duplicate-key errors on result_awards.
SET session_replication_role = replica;

EOF

cat "$SEED_FILE.tmp2" >> "$SEED_FILE"

# Re-enable triggers for normal operation after the bulk load.
printf '\n-- Re-enable triggers for normal operation after the bulk load.\nSET session_replication_role = DEFAULT;\n' >> "$SEED_FILE"

# Clean up temp files
rm -f "$SEED_FILE.tmp" "$SEED_FILE.tmp2"

# Generate rider_memberships seed (contains PII — gitignored)
MEMBERSHIPS_FILE="supabase/seed-memberships.sql"

docker exec "$CONTAINER" pg_dump -U postgres \
  --data-only \
  --inserts \
  --column-inserts \
  --no-comments \
  --rows-per-insert=1 \
  --schema=public \
  --table=rider_memberships \
  postgres > "$MEMBERSHIPS_FILE.tmp"

grep -E "^INSERT INTO" "$MEMBERSHIPS_FILE.tmp" > "$MEMBERSHIPS_FILE.tmp2" || true

# Generate rider PII UPDATE statements from the database
# (restores email, emergency contacts, ccn_id, birth_year stripped from seed.sql)
docker exec "$CONTAINER" psql -U postgres -d postgres -At -c "
  SELECT 'UPDATE public.riders SET '
    || 'email = ' || COALESCE(quote_literal(email), 'NULL')
    || ', emergency_contact_name = ' || COALESCE(quote_literal(emergency_contact_name), 'NULL')
    || ', emergency_contact_phone = ' || COALESCE(quote_literal(emergency_contact_phone), 'NULL')
    || ', ccn_id = ' || COALESCE(ccn_id::text, 'NULL')
    || ', birth_year = ' || COALESCE(birth_year::text, 'NULL')
    || ' WHERE id = ' || quote_literal(id) || ';'
  FROM public.riders
  WHERE email IS NOT NULL
     OR emergency_contact_name IS NOT NULL
     OR emergency_contact_phone IS NOT NULL
     OR ccn_id IS NOT NULL
     OR birth_year IS NOT NULL
  ORDER BY last_name, first_name;
" > "$MEMBERSHIPS_FILE.rider_pii" || true

cat > "$MEMBERSHIPS_FILE" << 'EOF'
-- Rider PII and memberships seed data (contains PII — DO NOT commit)
-- Generated by scripts/generate-seed.sh
--
-- Run after the main seed.sql:
--   psql -h localhost -p 54322 -U postgres -d postgres -f supabase/seed-memberships.sql

-- Restore rider PII (email, emergency contacts, ccn_id, birth_year)
EOF

cat "$MEMBERSHIPS_FILE.rider_pii" >> "$MEMBERSHIPS_FILE"

echo "" >> "$MEMBERSHIPS_FILE"
echo "-- Rider memberships" >> "$MEMBERSHIPS_FILE"
cat "$MEMBERSHIPS_FILE.tmp2" >> "$MEMBERSHIPS_FILE"
rm -f "$MEMBERSHIPS_FILE.tmp" "$MEMBERSHIPS_FILE.tmp2" "$MEMBERSHIPS_FILE.rider_pii"

# Generate production update script (idempotent, contains PII — gitignored)
PROD_FILE="supabase/prod-membership-update.sql"

cat > "$PROD_FILE" << 'EOF'
-- Production membership update (contains PII — DO NOT commit)
-- Generated by scripts/generate-seed.sh
--
-- Idempotent: safe to run multiple times.
-- Usage: psql "<production-connection-string>" -f supabase/prod-membership-update.sql

BEGIN;

-- Section 1: Upsert riders (creates new riders, updates existing with PII fields)
EOF

# Generate rider upserts for riders that have any enriched data
docker exec "$CONTAINER" psql -U postgres -d postgres -At -c "
  SELECT 'INSERT INTO public.riders (id, slug, first_name, last_name, email, gender, ccn_id, birth_year, member_since) VALUES ('
    || quote_literal(id) || ', '
    || quote_literal(slug) || ', '
    || quote_literal(first_name) || ', '
    || quote_literal(last_name) || ', '
    || COALESCE(quote_literal(email), 'NULL') || ', '
    || COALESCE(quote_literal(gender), 'NULL') || ', '
    || COALESCE(ccn_id::text, 'NULL') || ', '
    || COALESCE(birth_year::text, 'NULL') || ', '
    || COALESCE(member_since::text, 'NULL')
    || ') ON CONFLICT (id) DO UPDATE SET '
    || 'email = COALESCE(EXCLUDED.email, public.riders.email), '
    || 'gender = COALESCE(EXCLUDED.gender, public.riders.gender), '
    || 'ccn_id = COALESCE(EXCLUDED.ccn_id, public.riders.ccn_id), '
    || 'birth_year = COALESCE(EXCLUDED.birth_year, public.riders.birth_year), '
    || 'member_since = COALESCE(EXCLUDED.member_since, public.riders.member_since);'
  FROM public.riders
  WHERE email IS NOT NULL
     OR gender IS NOT NULL
     OR ccn_id IS NOT NULL
     OR birth_year IS NOT NULL
  ORDER BY last_name, first_name;
" >> "$PROD_FILE" || true

echo "" >> "$PROD_FILE"
echo "-- Section 2: Upsert rider_memberships" >> "$PROD_FILE"

# Generate rider_memberships upserts
docker exec "$CONTAINER" psql -U postgres -d postgres -At -c "
  SELECT 'INSERT INTO public.rider_memberships (rider_id, season, chapter_id, membership_type, city, province, country, ccn_id) VALUES ('
    || quote_literal(rider_id) || ', '
    || season || ', '
    || COALESCE(quote_literal(chapter_id), 'NULL') || ', '
    || quote_literal(membership_type) || ', '
    || COALESCE(quote_literal(city), 'NULL') || ', '
    || COALESCE(quote_literal(province), 'NULL') || ', '
    || COALESCE(quote_literal(country), 'NULL') || ', '
    || COALESCE(ccn_id::text, 'NULL')
    || ') ON CONFLICT (rider_id, season) DO NOTHING;'
  FROM public.rider_memberships
  ORDER BY season, rider_id;
" >> "$PROD_FILE" || true

echo "" >> "$PROD_FILE"
echo "COMMIT;" >> "$PROD_FILE"

# Count records
echo ""
echo "Seed file generated: $SEED_FILE"
echo ""
echo "Record counts:"
echo "  chapters:      $(grep -c "INSERT INTO public.chapters" "$SEED_FILE" || true)"
echo "  awards:        $(grep -c "INSERT INTO public.awards" "$SEED_FILE" || true)"
echo "  riders:        $(grep -c "INSERT INTO public.riders" "$SEED_FILE" || true)"
echo "  routes:        $(grep -c "INSERT INTO public.routes" "$SEED_FILE" || true)"
echo "  events:        $(grep -c "INSERT INTO public.events" "$SEED_FILE" || true)"
echo "  results:       $(grep -c "INSERT INTO public.results" "$SEED_FILE" || true)"
echo "  result_awards: $(grep -c "INSERT INTO public.result_awards" "$SEED_FILE" || true)"
echo "  rider_awards:  $(grep -c "INSERT INTO public.rider_awards" "$SEED_FILE" || true)"
echo "  registrations: $(grep -c "INSERT INTO public.registrations" "$SEED_FILE" || true)"
echo ""
echo "File size: $(du -h "$SEED_FILE" | cut -f1)"
echo ""
echo "Production update: $PROD_FILE (gitignored)"
echo "  rider upserts:      $(grep -c "INSERT INTO public.riders" "$PROD_FILE" || true)"
echo "  membership upserts: $(grep -c "INSERT INTO public.rider_memberships" "$PROD_FILE" || true)"
echo "  File size: $(du -h "$PROD_FILE" | cut -f1)"
echo ""
echo "PII overlay: $MEMBERSHIPS_FILE (gitignored)"
echo "  rider PII updates: $(grep -c "UPDATE public.riders" "$MEMBERSHIPS_FILE" || true)"
echo "  rider_memberships: $(grep -c "INSERT INTO public.rider_memberships" "$MEMBERSHIPS_FILE" || true)"
echo "  File size: $(du -h "$MEMBERSHIPS_FILE" | cut -f1)"
