#!/bin/bash
# Generate a clean seed.sql file from the current database state
# This avoids the backslash escape issues that pg_dump can introduce

set -e

SEED_FILE="supabase/seed.sql"
CONTAINER="supabase_db_randonneurs-ontario"

echo "Generating seed file from current database…"

# Generate the dump with INSERT statements using pg_dump from inside Docker
# (to avoid version mismatch issues)
# --data-only: Only data, no schema
# --inserts: Use INSERT instead of COPY (avoids escape issues)
# --column-inserts: Include column names in INSERT statements
# --no-comments: Skip comments
# --rows-per-insert=1: One row per INSERT for easier debugging
docker exec "$CONTAINER" pg_dump -U postgres \
  --data-only \
  --inserts \
  --column-inserts \
  --no-comments \
  --rows-per-insert=1 \
  --schema=public \
  --exclude-table=admins \
  postgres > "$SEED_FILE.tmp"

# Clean up the file:
# 1. Remove SET statements (they can cause issues)
# 2. Remove backslash commands like \connect, \restrict
# 3. Remove empty lines at the start
# 4. Keep only INSERT statements and necessary transaction commands
grep -E "^(INSERT INTO|SELECT pg_catalog|--|$)" "$SEED_FILE.tmp" | \
  grep -v "^--" | \
  grep -v "^SELECT pg_catalog" | \
  grep -v "^$" > "$SEED_FILE.tmp2" || true

# Convert chapter INSERTs to use ON CONFLICT DO UPDATE
# This ensures correct UUIDs even when migrations have already inserted some chapters
# The migration uses ON CONFLICT DO NOTHING, so seed needs to update the IDs
sed -i.bak 's/INSERT INTO public\.chapters (\([^)]*\)) VALUES (\([^)]*\));/INSERT INTO public.chapters (\1) VALUES (\2) ON CONFLICT (slug) DO UPDATE SET id = EXCLUDED.id, name = EXCLUDED.name, description = EXCLUDED.description, founded_year = EXCLUDED.founded_year;/' "$SEED_FILE.tmp2"
rm -f "$SEED_FILE.tmp2.bak"

# Add a header and the cleaned INSERT statements
cat > "$SEED_FILE" << 'EOF'
-- Seed data for Randonneurs Ontario
-- Generated by scripts/generate-seed.sh
--
-- Note: This file is auto-generated. Do not edit manually.
-- To regenerate: ./scripts/generate-seed.sh
--
-- Tables seeded (in order):
-- 1. chapters
-- 2. awards
-- 3. riders
-- 4. routes
-- 5. events
-- 6. results
-- 7. result_awards
-- 8. registrations
--
-- Note: admins table is NOT included (requires auth.users)
-- Use scripts/create-admin.ts to create admin users after seeding.

EOF

cat "$SEED_FILE.tmp2" >> "$SEED_FILE"

# Clean up temp files
rm -f "$SEED_FILE.tmp" "$SEED_FILE.tmp2"

# Count records
echo ""
echo "Seed file generated: $SEED_FILE"
echo ""
echo "Record counts:"
echo "  chapters:      $(grep -c "INSERT INTO public.chapters" "$SEED_FILE" || echo 0)"
echo "  awards:        $(grep -c "INSERT INTO public.awards" "$SEED_FILE" || echo 0)"
echo "  riders:        $(grep -c "INSERT INTO public.riders" "$SEED_FILE" || echo 0)"
echo "  routes:        $(grep -c "INSERT INTO public.routes" "$SEED_FILE" || echo 0)"
echo "  events:        $(grep -c "INSERT INTO public.events" "$SEED_FILE" || echo 0)"
echo "  results:       $(grep -c "INSERT INTO public.results" "$SEED_FILE" || echo 0)"
echo "  result_awards: $(grep -c "INSERT INTO public.result_awards" "$SEED_FILE" || echo 0)"
echo "  registrations: $(grep -c "INSERT INTO public.registrations" "$SEED_FILE" || echo 0)"
echo ""
echo "File size: $(du -h "$SEED_FILE" | cut -f1)"
